import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const dumpFile = path.join(__dirname, 'data', 'old_db_dump.json');
const schemaFile = path.join(__dirname, 'schema.sql');
const importScriptFile = path.join(__dirname, 'import_data.js');

const dump = JSON.parse(fs.readFileSync(dumpFile, 'utf8'));

// Helper to guess type
function guessType(table, column, value) {
    // Overrides based on knowledge or supabase.md
    if (column === 'id' && table === 'otto_tr_h') return 'BIGINT GENERATED BY DEFAULT AS IDENTITY';
    if (column === 'id' && table === 'otto_tr_t') return 'BIGINT'; // FK to header
    if (column === 'id' && typeof value === 'number') return 'BIGINT GENERATED BY DEFAULT AS IDENTITY';
    if (column === 'id' && typeof value === 'string') return 'TEXT'; // For uuid
    if (column === 'device_id') return 'JSONB';
    if (column === 'created_at' || column === 'updated_at' || column === 'expires_at' || column === 'last_accessed_at') return 'TIMESTAMP WITH TIME ZONE';
    if (column === 'invoicedate' || column === 'fromdate' || column === 'todate') return 'DATE';
    if (column === 'tr_amount') return 'TEXT'; // Per MD
    
    if (typeof value === 'boolean') return 'BOOLEAN';
    if (typeof value === 'number') return 'NUMERIC';
    if (typeof value === 'object' && value !== null) return 'JSONB';
    return 'TEXT';
}

// Generate Schema
let sql = '-- Migration Schema generated from introspection\n\n';

// Table creation order (independent first)
const tables = Object.keys(dump);
// We need to order them manually to avoid FK issues during creation if we add constraints inline.
// But for simplicity, we can create tables then add constraints, or just follow a known order.
const orderedTables = [
    'otto_user',
    'otto_role',
    'otto_customer',
    'otto_project',
    'otto_travelentry',
    'otto_invoices',
    'otto_tr_h',
    'otto_tr_t',
    'otto_userrole',
    't_loginsessions'
];

// PK definitions known from MD
const pks = {
    'otto_user': ['userid'],
    'otto_role': ['roleid'],
    'otto_userrole': ['userid', 'roleid'],
    'otto_customer': ['customerid'],
    'otto_project': ['projectid'],
    'otto_travelentry': ['travelid'],
    'otto_invoices': ['invoiceno'],
    'otto_tr_h': ['id'],
    'otto_tr_t': ['id', 'invoiceno'],
    't_loginsessions': ['session_id']
};

orderedTables.forEach(table => {
    if (!dump[table]) return;
    const { columns, data } = dump[table];
    const sample = data.find(d => d !== null) || {};
    
    sql += `CREATE TABLE IF NOT EXISTS ${table} (\n`;
    
    const colDefs = columns.map(col => {
        // Find a non-null value for this column to guess type
        let val = null;
        for (const row of data) {
            if (row[col] !== null && row[col] !== undefined) {
                val = row[col];
                break;
            }
        }
        const type = guessType(table, col, val);
        return `    "${col}" ${type}`;
    });

    // Add PK
    if (pks[table]) {
        colDefs.push(`    PRIMARY KEY (${pks[table].map(k => `"${k}"`).join(', ')})`);
    }

    sql += colDefs.join(',\n');
    sql += '\n);\n\n';
});

// Add FKs (Separate to avoid ordering issues if we were strictly generating DDL, 
// but here we just append them. Note: order of execution matters for constraints if tables don't exist,
// but we created all tables above.)

// We will add basic FKs based on name matching or MD
sql += `-- Foreign Keys\n`;
sql += `ALTER TABLE otto_userrole ADD CONSTRAINT fk_userrole_user FOREIGN KEY (userid) REFERENCES otto_user(userid);\n`;
sql += `ALTER TABLE otto_userrole ADD CONSTRAINT fk_userrole_role FOREIGN KEY (roleid) REFERENCES otto_role(roleid);\n`;
sql += `ALTER TABLE otto_project ADD CONSTRAINT fk_project_customer FOREIGN KEY (customerid) REFERENCES otto_customer(customerid);\n`;
// otto_project.projectmanager -> otto_user.userid? MD says so.
sql += `ALTER TABLE otto_project ADD CONSTRAINT fk_project_manager FOREIGN KEY (projectmanager) REFERENCES otto_user(userid);\n`;
sql += `ALTER TABLE otto_travelentry ADD CONSTRAINT fk_travel_user FOREIGN KEY (userid) REFERENCES otto_user(userid);\n`;
sql += `ALTER TABLE otto_travelentry ADD CONSTRAINT fk_travel_project FOREIGN KEY (projectid) REFERENCES otto_project(projectid);\n`;
// invoices.travelid can be null, so simple FK is fine
sql += `ALTER TABLE otto_invoices ADD CONSTRAINT fk_invoice_travel FOREIGN KEY (travelid) REFERENCES otto_travelentry(travelid);\n`;
// otto_tr_t links to otto_tr_h(id) and otto_invoices(invoiceno)
sql += `ALTER TABLE otto_tr_t ADD CONSTRAINT fk_trt_header FOREIGN KEY (id) REFERENCES otto_tr_h(id);\n`;
sql += `ALTER TABLE otto_tr_t ADD CONSTRAINT fk_trt_invoice FOREIGN KEY (invoiceno) REFERENCES otto_invoices(invoiceno);\n`;


fs.writeFileSync(schemaFile, sql);
console.log(`Generated ${schemaFile}`);

// Generate Import Script
const importScriptContent = `
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// NEW Supabase Credentials (passed via env or hardcoded placeholder)
const NEW_SUPABASE_URL = process.env.NEW_SUPABASE_URL || 'https://spb-ks0bkv1uqa7cgru8.supabase.opentrust.net';
const NEW_SUPABASE_KEY = process.env.NEW_SUPABASE_KEY; // Service Role Key REQUIRED

if (!NEW_SUPABASE_KEY) {
    console.error('Error: NEW_SUPABASE_KEY environment variable is required (Service Role Key).');
    process.exit(1);
}

const supabase = createClient(NEW_SUPABASE_URL, NEW_SUPABASE_KEY);

const dumpFile = path.join(__dirname, 'data', 'old_db_dump.json');
const dump = JSON.parse(fs.readFileSync(dumpFile, 'utf8'));

// Order matters for data import due to FKs
const importOrder = [
    'otto_user',
    'otto_role',
    'otto_customer',
    'otto_project', // depends on customer, user
    'otto_travelentry', // depends on user, project
    'otto_invoices', // depends on travelentry
    'otto_tr_h', // depends on user
    'otto_tr_t', // depends on tr_h, invoices
    'otto_userrole', // depends on user, role
    't_loginsessions' // depends on user (logical)
];

async function importData() {
    console.log('Starting data import to ' + NEW_SUPABASE_URL);

    for (const table of importOrder) {
        if (!dump[table]) continue;
        const { data } = dump[table];
        if (!data || data.length === 0) continue;

        console.log(\`Importing \${data.length} rows into \${table}...\`);
        
        // Batch insert to avoid payload limits
        const batchSize = 100;
        for (let i = 0; i < data.length; i += batchSize) {
            const batch = data.slice(i, i + batchSize);
            const { error } = await supabase.from(table).upsert(batch);
            
            if (error) {
                console.error(\`Error importing batch \${i} for \${table}:\`, error);
                // Continue with next batch or stop?
                // process.exit(1); 
            }
        }
    }
    console.log('Import completed.');
}

importData().catch(console.error);
`;

fs.writeFileSync(importScriptFile, importScriptContent);
console.log(`Generated ${importScriptFile}`);
