import pg from 'pg';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const { Client } = pg;
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Construct connection string from user input
const connectionString = 'postgres://postgres:Randoll1230@spb-ks0bkv1uqa7cgru8.supabase.opentrust.net:5432/postgres';

const client = new Client({
  connectionString,
  // ssl: { rejectUnauthorized: false } // Server does not support SSL?
});

async function migrate() {
  try {
    console.log('Connecting to PostgreSQL...');
    await client.connect();
    console.log('Connected successfully!');

    // 1. Run Schema
    const schemaPath = path.join(__dirname, 'schema.sql');
    const schemaSql = fs.readFileSync(schemaPath, 'utf8');
    
    console.log('Running schema migration...');
    // Split commands by semicolon if needed, but pg usually handles it or we can just send the block.
    // However, CREATE TABLE IF NOT EXISTS is safe.
    // ALTER TABLE usually fails if constraint exists.
    // Let's wrap constraint addition in DO block or just try/catch?
    // Or just run it. If it fails due to existing constraint, migration stops.
    // Better to just run it. If it's a fresh DB, it works.
    
    // We'll replace ALTER TABLE with safe versions or just run the whole thing.
    // Given the user said "new environment", it should be empty.
    
    try {
      await client.query(schemaSql);
      console.log('Schema created successfully.');
    } catch (schemaErr) {
      if (schemaErr?.code === '42710' || schemaErr?.code === '42P07') {
        console.warn(
          `Schema objects already exist (${schemaErr.code}). Continuing with data import...`,
        );
      } else {
        throw schemaErr;
      }
    }

    // 2. Import Data
    const dumpPath = path.join(__dirname, 'data', 'old_db_dump.json');
    const dump = JSON.parse(fs.readFileSync(dumpPath, 'utf8'));

    // Order matters
    const importOrder = [
        'otto_user',
        'otto_role',
        'otto_customer',
        'otto_project', 
        'otto_travelentry', 
        'otto_invoices', 
        'otto_tr_h', 
        'otto_tr_t', 
        'otto_userrole', 
        't_loginsessions' 
    ];

    const tableColumnsCache = new Map();
    async function getTableColumns(table) {
      if (tableColumnsCache.has(table)) {
        return tableColumnsCache.get(table);
      }
      const result = await client.query(
        `SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1`,
        [table],
      );
      const cols = new Set(result.rows.map((r) => r.column_name));
      tableColumnsCache.set(table, cols);
      return cols;
    }

    for (const table of importOrder) {
        if (!dump[table]) continue;
        const { data } = dump[table];
        if (!data || data.length === 0) continue;

        console.log(`Importing ${data.length} rows into ${table}...`);
        
        let successCount = 0;
        let errorCount = 0;

        const dbColumns = await getTableColumns(table);
        for (const row of data) {
            const columns = Object.keys(row).filter((c) => dbColumns.has(c));
            if (columns.length === 0) {
                errorCount++;
                continue;
            }
            const values = columns.map((c) => row[c]);
            
            // Construct param query
            const placeholders = values.map((_, i) => `$${i + 1}`).join(', ');
            const insertSql = `INSERT INTO "${table}" ("${columns.join('", "')}") VALUES (${placeholders}) ON CONFLICT DO NOTHING`;
            
            try {
                await client.query(insertSql, values);
                successCount++;
            } catch (err) {
                // Ignore unique constraint violations (handled by ON CONFLICT DO NOTHING anyway, but just in case)
                console.error(`Error inserting into ${table}:`, err.message);
                errorCount++;
            }
        }
        console.log(`  - Success: ${successCount}, Errors: ${errorCount}`);
    }

    // 3. Reset Sequences
    console.log('Resetting sequences...');
    const sequences = [
        { table: 'otto_tr_h', col: 'id' },
        { table: 'otto_tr_t', col: 'id' } // wait, otto_tr_t id is not serial in schema.sql?
    ];
    // schema.sql: otto_tr_h.id BIGINT GENERATED BY DEFAULT AS IDENTITY
    // otto_tr_t.id BIGINT (FK)
    // So only otto_tr_h needs reset.

    try {
        await client.query(`SELECT setval(pg_get_serial_sequence('otto_tr_h', 'id'), coalesce(max(id),0) + 1, false) FROM otto_tr_h;`);
        console.log('Sequence for otto_tr_h reset.');
    } catch (err) {
        console.warn('Could not reset sequence (might be fine if no data or not serial):', err.message);
    }
    
    console.log('Migration completed successfully.');

  } catch (err) {
    console.error('Migration failed:', err);
  } finally {
    await client.end();
  }
}

migrate();
