-- Migration Schema generated from introspection

CREATE TABLE IF NOT EXISTS otto_user (
    "userid" TEXT,
    "email" TEXT,
    "firstname" TEXT,
    "lastname" TEXT,
    "mobile" TEXT,
    "password" TEXT,
    "sap_supplier_id" VARCHAR(10),
    PRIMARY KEY ("userid")
);

CREATE TABLE IF NOT EXISTS otto_role (
    "roleid" TEXT,
    "description" TEXT,
    PRIMARY KEY ("roleid")
);

CREATE TABLE IF NOT EXISTS otto_customer (
    "customerid" TEXT,
    "taxcode" TEXT,
    "customername" TEXT,
    "address" TEXT,
    "contactperson" TEXT,
    "mobile" TEXT,
    "fullname_zh" TEXT,
    "fullname_en" TEXT,
    "email" TEXT,
    PRIMARY KEY ("customerid")
);

CREATE TABLE IF NOT EXISTS otto_project (
    "projectid" TEXT,
    "customerid" TEXT,
    "description" TEXT,
    "trchargeable" BOOLEAN,
    "txchargeable" BOOLEAN,
    "projectmanager" TEXT,
    PRIMARY KEY ("projectid")
);

CREATE TABLE IF NOT EXISTS otto_travelentry (
    "travelid" TEXT,
    "userid" TEXT,
    "fromdate" DATE,
    "todate" DATE,
    "destination" TEXT,
    "projectid" TEXT,
    PRIMARY KEY ("travelid")
);

CREATE TABLE IF NOT EXISTS otto_invoices (
    "invoiceno" TEXT,
    "travelid" TEXT,
    "userid" TEXT,
    "invoicedate" DATE,
    "totalnetamount" NUMERIC,
    "taxamount" NUMERIC,
    "grossamount" NUMERIC,
    "bookingcode" TEXT,
    "businesstype" TEXT NOT NULL DEFAULT '03' CHECK ("businesstype" IN ('01', '02', '03')),
    "currency" TEXT,
    "originalamount" NUMERIC,
    "originalcurrency" TEXT,
    "status" TEXT,
    "comment" TEXT,
    "description" TEXT,
    "supplier" TEXT,
    PRIMARY KEY ("invoiceno")
);

CREATE TABLE IF NOT EXISTS otto_invoice_lines (
    "invoiceno" TEXT NOT NULL,
    "seqno" INTEGER NOT NULL CHECK ("seqno" > 0),
    "description" TEXT NOT NULL DEFAULT '',
    "spec_model" TEXT,
    "unit_price" NUMERIC,
    "quantity" NUMERIC,
    "amount_excl_tax" NUMERIC,
    "tax_rate" TEXT,
    "amount_incl_tax" NUMERIC,
    PRIMARY KEY ("invoiceno", "seqno")
);

CREATE TABLE IF NOT EXISTS otto_booking_rule (
    "code" TEXT PRIMARY KEY,
    "category" TEXT NOT NULL,
    "name_zh" TEXT NOT NULL,
    "name_en" TEXT,
    "description" TEXT,
    "keywords" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "costcenter" TEXT,
    "accountingsubject" TEXT,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS otto_tr_h (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "userid" TEXT,
    "projectid" TEXT,
    "trno" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE,
    "bookingstatus" TEXT,
    "approvalstatus" TEXT,
    "approver" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS otto_tr_t (
    "id" BIGINT,
    "invoiceno" TEXT,
    "seqno" INTEGER NOT NULL,
    "tr_amount" TEXT,
    "trchargeable" BOOLEAN,
    "txchargeable" BOOLEAN,
    PRIMARY KEY ("id", "invoiceno"),
    UNIQUE ("id", "seqno")
);

CREATE TABLE IF NOT EXISTS otto_userrole (
    "userid" TEXT,
    "roleid" TEXT,
    PRIMARY KEY ("userid", "roleid")
);

CREATE TABLE IF NOT EXISTS t_loginsessions (
    "session_id" TEXT,
    "userid" TEXT,
    "expires_at" TIMESTAMP WITH TIME ZONE,
    "created_at" TIMESTAMP WITH TIME ZONE,
    "updated_at" TIMESTAMP WITH TIME ZONE,
    "last_accessed_at" TIMESTAMP WITH TIME ZONE,
    "ip_address" TEXT,
    "is_active" BOOLEAN,
    "device_id" JSONB,
    "cookie" TEXT,
    PRIMARY KEY ("session_id")
);

CREATE TABLE IF NOT EXISTS reimbursement_approval_tokens (
    "token" TEXT,
    "reimbursement_id" BIGINT,
    "approver_userid" TEXT,
    "expires_at" TIMESTAMP WITH TIME ZONE,
    "used_at" TIMESTAMP WITH TIME ZONE,
    "used_action" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY ("token")
);

-- Foreign Keys
ALTER TABLE otto_userrole ADD CONSTRAINT fk_userrole_user FOREIGN KEY (userid) REFERENCES otto_user(userid);
ALTER TABLE otto_userrole ADD CONSTRAINT fk_userrole_role FOREIGN KEY (roleid) REFERENCES otto_role(roleid);
ALTER TABLE otto_project ADD CONSTRAINT fk_project_customer FOREIGN KEY (customerid) REFERENCES otto_customer(customerid);
ALTER TABLE otto_project ADD CONSTRAINT fk_project_manager FOREIGN KEY (projectmanager) REFERENCES otto_user(userid);
ALTER TABLE otto_travelentry ADD CONSTRAINT fk_travel_user FOREIGN KEY (userid) REFERENCES otto_user(userid);
ALTER TABLE otto_travelentry ADD CONSTRAINT fk_travel_project FOREIGN KEY (projectid) REFERENCES otto_project(projectid);
ALTER TABLE otto_invoices ADD CONSTRAINT fk_invoice_travel FOREIGN KEY (travelid) REFERENCES otto_travelentry(travelid);
ALTER TABLE otto_invoice_lines ADD CONSTRAINT fk_invoice_line_invoice FOREIGN KEY (invoiceno) REFERENCES otto_invoices(invoiceno) ON DELETE CASCADE;
ALTER TABLE otto_tr_h ADD CONSTRAINT fk_trh_project FOREIGN KEY (projectid) REFERENCES otto_project(projectid);
ALTER TABLE otto_tr_t ADD CONSTRAINT fk_trt_header FOREIGN KEY (id) REFERENCES otto_tr_h(id);
ALTER TABLE otto_tr_t ADD CONSTRAINT fk_trt_invoice FOREIGN KEY (invoiceno) REFERENCES otto_invoices(invoiceno);

ALTER TABLE otto_tr_t ADD COLUMN IF NOT EXISTS trchargeable BOOLEAN;
ALTER TABLE otto_tr_t ADD COLUMN IF NOT EXISTS txchargeable BOOLEAN;
ALTER TABLE otto_invoices ADD COLUMN IF NOT EXISTS originalamount NUMERIC;
ALTER TABLE otto_invoices ADD COLUMN IF NOT EXISTS originalcurrency TEXT;
ALTER TABLE otto_user ADD COLUMN IF NOT EXISTS sap_supplier_id VARCHAR(10);

-- Reimbursement report all-in-one view
CREATE OR REPLACE VIEW otto_v_tr_all AS
SELECT
  h.id AS tr_id,
  COALESCE(NULLIF(h.trno, ''), h.id::TEXT) AS trno,
  h.created_at AS tr_created_at,
  h.userid AS tr_userid,
  TRIM(CONCAT_WS(' ', applicant.firstname, applicant.lastname)) AS tr_user_name,
  h.projectid AS tr_projectid,
  p.description AS project_description,
  p.projectmanager AS project_manager_userid,
  TRIM(CONCAT_WS(' ', pm.firstname, pm.lastname)) AS project_manager_name,
  p.customerid,
  c.customername,
  h.approvalstatus,
  h.bookingstatus,
  h.approver AS approver_userid,
  TRIM(CONCAT_WS(' ', approver_u.firstname, approver_u.lastname)) AS approver_name,
  t.invoiceno,
  NULLIF(TRIM(t.tr_amount), '')::NUMERIC AS tr_amount,
  t.trchargeable AS line_trchargeable,
  t.txchargeable AS line_txchargeable,
  i.userid AS invoice_userid,
  TRIM(CONCAT_WS(' ', invoice_u.firstname, invoice_u.lastname)) AS invoice_user_name,
  i.travelid,
  te.fromdate AS travel_fromdate,
  te.todate AS travel_todate,
  te.destination AS travel_destination,
  i.invoicedate,
  i.totalnetamount,
  i.taxamount,
  i.grossamount,
  i.bookingcode,
  i.currency,
  i.status AS invoice_status,
  i.comment AS invoice_comment,
  i.description AS invoice_description,
  i.supplier AS invoice_supplier,
  t.seqno AS tr_seqno
FROM otto_tr_h h
LEFT JOIN otto_project p ON p.projectid = h.projectid
LEFT JOIN otto_customer c ON c.customerid = p.customerid
LEFT JOIN otto_user applicant ON applicant.userid = h.userid
LEFT JOIN otto_user pm ON pm.userid = p.projectmanager
LEFT JOIN otto_user approver_u ON approver_u.userid = h.approver
LEFT JOIN otto_tr_t t ON t.id = h.id
LEFT JOIN otto_invoices i ON i.invoiceno = t.invoiceno
LEFT JOIN otto_travelentry te ON te.travelid = i.travelid
LEFT JOIN otto_user invoice_u ON invoice_u.userid = i.userid;

-- Durable upload queue. File bytes live in persistent server storage.
CREATE TABLE IF NOT EXISTS otto_supplier_invoice_drafts (
  id UUID PRIMARY KEY,
  userid TEXT NOT NULL,
  filename TEXT NOT NULL,
  storage_key TEXT NOT NULL UNIQUE,
  content_type TEXT NOT NULL,
  file_size BIGINT NOT NULL CHECK (file_size > 0),
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued','recognizing','ready','editing','saved','error')),
  header JSONB NOT NULL DEFAULT '{}'::jsonb,
  lines JSONB NOT NULL DEFAULT '[]'::jsonb,
  recognized_result JSONB,
  error TEXT,
  version INTEGER NOT NULL DEFAULT 1,
  lease_token UUID,
  lease_until TIMESTAMPTZ,
  saved_invoice_no TEXT UNIQUE REFERENCES otto_invoices(invoiceno) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (header->>'businesstype' IN ('01','02'))
);
CREATE INDEX IF NOT EXISTS idx_supplier_drafts_user ON otto_supplier_invoice_drafts(userid, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_drafts_queue ON otto_supplier_invoice_drafts(status, lease_until, created_at);
-- Access only through authenticated server services, never anonymous Supabase REST.
ALTER TABLE otto_supplier_invoice_drafts ENABLE ROW LEVEL SECURITY;

-- Administrator-managed settings and a shared admission gate for invoice recognition.
CREATE TABLE IF NOT EXISTS otto_system_config (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(value) = 'object'),
  version INTEGER NOT NULL DEFAULT 1,
  updated_by TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO otto_system_config(key) VALUES ('invoice_recognition') ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS otto_invoice_recognition_leases (
  id UUID PRIMARY KEY,
  expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_invoice_recognition_lease_expiry ON otto_invoice_recognition_leases(expires_at);
ALTER TABLE otto_system_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE otto_invoice_recognition_leases ENABLE ROW LEVEL SECURITY;
-- No anonymous policies: these tables are accessed by the server database role only.
